package com.quizeserver.quizserver.dto;

import lombok.Data;
import java.util.List;

@Data
public class TestDTO {

    private Long id;
    private String title;
    private String description;
    private int time;

    private List<QuestionDTO> questions; // Add this field for questions

    // Getters and setters will be generated by Lombok (@Data)
}
